= Axiia 评估人类驾驭AI的能力
:author: Yihan Zhou
:toclevels: 3
:toc: left
:email: yihan@axiia.ai



## 评估 AI力

AI力: 人类驾驭AI的能力

### Why

IMPORTANT: AI #增加# 了人与人之间的 #差距#.

使用AI的能力是未来杠杆最高的能力。一个AI使用好的的人的工作效率可以是一个AI用的不好的人的10倍。

未来，所有仍需人类的参与的工作，都会和AI共同完成。
未来人与人的最重要差距就是使用AI能力的差距。
组织之间的主要差距，在于谁擅长识别能驾驭AI的人.

NOTE: 人们不追求评估的多样性, 评估是天然的垄断市场: 一个 #*万亿市场*#.


### What

我们希望定义, 评估这些能力. 我们从两个维度定义AI力:

从人和AI交互环节的维度::
提问能力::: 用准确的语言降低自己的未知,
指挥能力::: 明确的表达希望 AI 做的事情,
检验能力::: 判断 AI 的工作成果是否符合要求,
迭代能力::: 有技巧的, 目标导向的重复以上环节;

从人对AI交付内容的维度::
定义目标能力::: 不论AI如何强大, 人都需要传达给 AI 自己的需求: 在很多复杂问题上, 如系统设计, 清晰的定义目标本身就已经解决了一半的问题
* 此能力的需求随 AI 的发展会愈加重要
* 此能力和今日的领导力, 战略规划能力有相似, 但不同, 因为不需要考虑被指挥者的情绪

定义抽象过程能力::: 当 AI 能力不足以直接实现人类给出的目标, 人就需要教给 AI 达成目标的过程; 抽象过程的定义需要人能通过总结具体案例, 提炼出解决问题的步骤;
* 此能力的需求中长期内一直存在, 极长期后随 AI 发展略微下降
* 此能力今日在非工程背景的人群中尤为缺乏, 很多人看重眼前工作的完成, 而忽视了方法论的沉淀

具体工具应用能力::: 今日有很多工具, 如果熟练掌握, 可以大大提升人对 AI 的驾驭, 如claude prompt generator, DSPY, 等. 甚至对 chatgpt 本身的prompting 技巧也可以视为一种对工具的掌握程度
* 此能力会随着 AI 工具和底层模型能力的发展而快速变化, 需要不断学习, 对工具的学习能力在长远来看比对具体工具的熟练更有价值
* 如同不断更新的编程语言特性, 前端框架, 机器学习架构等, 需要工程师们不断学习


### GTM: 提示词能力评估

AI力在中长期的未来, 会普及成每个公司, 每个人都必要的能力.
在短期, AI力是部分公司紧迫需要的能力.
今天, 很多 AI 创业公司都对好的提示词工程师有非常紧迫的需求, 以部分我们在洽谈的客户为例:



[CAUTION]
====

鉴于客户隐私, 在公开版本我们略去了客户案例, 有兴趣的朋友可联系
info@axiia.ai 获取


====






#### 市场进展
NOTE: 大家都不知道如何评估这样一个全新的岗位.

这些公司此刻使用面试+试用期的评估方式, 成本高, 效率低, 效果差.
客户和我们确认了需求, 但作为一个评估产品, 客户也表达只有当我们的评估效果足够好时, 才会买单. 具体来说, 这里对好的定义是能给被试者进行有信效度的能力排名. 只要有排名, 客户就可以把评估结果整合进提示词人才的选, 用, 育, 留的流程内.



### How


NOTE: 人的水平 = 人与 AI 协作后的水平 - AI 的水平

NOTE: 评估的本质是一种预测: 它通过用户当前在测试中的行为预测用户将来在实际工作中的表现.


我们自研了出题智能体, 可以大量生成高质量的题目::
* 高质量的题目和实际工作场景高度相关. 所以, 我们的评估可以低成本的, 准确的预测用户将来的表现. 我们的题型包括:
** 大规模文本分析, 提取信息, 避免幻觉
** 写出让 AI 作出稳定判断的提示词
** 举出恰到好处的例子, 让 AI 理解自己的需求
** 根据提示词, 试图寻找 AI 可能的错误的输入输出对
** 等等
* 这些题目需要用户借助AI解决, 因为任务难度超出了人类难度完成的范畴, 当然也超出了 AI 单独完成的范畴
** 迫使用户必须有效利用 AI 工具
** 我们在测试中为用户提供了 gpt-4o 和 claude-3.5
** 避免了目前很多评估系统(面试, 在线笔试)的 AI 作弊问题, 因为我们的题目设计之初就是让人类使用 AI 来解决的.

我们在评估模型中建立壁垒::
常模搭建:::
* 刚结束200位适龄求职者在第三版题目上的测试, 1000人题次, 建立初版常模
* 常模是所有评估体系都需要的根基, 是人群水平分布的模型
* 同时我们根据本次测试, 建立的题目之间的相关度模型
* 随着之后更多的测试和真实使用, 我们的模型会 #越测越准#

符号回归:::
* 我们不止检验被试者的最终答案, 我们非常关注被试者解题的思维过程
* 通过本次测试, 我们收集大量用户和 AI 的协作解题聊天记录, 通过符号回归, 我们提取用户解题流程
** 我们正在挖掘流程和结果之间的相关性, 将来, #用户不需要专门做题, 我们可以根据其实际工作的过程, 对 AI力 直接进行评估#
** 同时, 这些解题过程也是优秀的 AI 训练数据, 因为收集思维过程数据是困难, 昂贵的

AI 力模型:::
根据题目之间的相关性, 我们抽象提取了 competency struct, 进一步验证了我们最开始对 AI力 的划分维度
* 提问, 指挥, 检验, 迭代
* 定义目标, 定义过程, 掌握工具




### 为什么不做教育?


为什么优先做评估::
. 评估是教育规模化的前提: 评估定义了教育的目标和学习的动机
. 教育会被AI根本性的改变, 现在做教育很快会被颠覆
** 以前无法做到每个人都能低成本, 随时, 获得高质量反馈
** 以后也许我们不需要上课, 只需要在实践中获得 AI 的反馈
. Axiia 要避免既做裁判, 又做教练, 从而保持评估的公信力, 才有机会成为标准制定者, 获得长远收益
** ETS 的托福和  GRE 比新东方常青
. 现在市面上有很多免费, 优质的 AI力 提升资源, 问题在于没有评估体系的情况下, 学习者和公司都无法确认学习效果
** 大模型公司的 prompt guide
** Andrew Ng 的网课

我们希望推动教育生态发展::
. 为 AI力 教育机构创造需求: 当 AI力 成为公司招聘重要考量时, AI力 教育会成为刚需
. 精准推荐课程: Axiia 根据被试者薄弱处, 推荐能最快提升被试者能力的学习材料, 成为部分教育机构的入口
. 协助教育机构定义教学大纲: Axiia 以终为始, 通过研究 AI力 和生产力对应关系, 定义教学目标, 从而反推教学大纲



## 产品延伸: 结构化提问

我们最关注的问题是: 人与 AI 交互体验的问题. 我们今天需要擅长这种交互的人类, 所以我们做了评估.
同时, 我们也在探索一款产品, 让 AI 更熟悉人类, 也更擅长跟人类交互. 这就是 Axiia-启问 .


今天很多人不擅长和 AI 协作的最大原因就是他们不擅长一次性的, 准确的表达他们的复杂的需求. 他们只能非常潦草的和 AI 表达需求, 然后看着 AI 的回复叹气.
这有些时候只是表达问题, 另外一些时候, 需求本身也并未想清楚.
今天多数 AI 创业和研究都在努力提高 AI 做事情的能力, 那么当 AI 足够强大, 整个系统的瓶颈就会出现在人和 AI 的交互上.


让一个人主动表达需求很难, 但是在恰当的, 引导性的提问下, 这个难度会大大降低.
考虑一个餐厅老板, 找了外包, 想做一个点餐 APP, 他也许很懂餐饮, 但是他不懂技术和产品.
所以, 他会很难表达自己的需求, 他可能会说, "我想要一个 KFC 那样的 APP", 但是很难描述细节.
这个时候如果直接按照 KFC 的 APP 开发, 做完之后, 老板一定会提很多意见, 就好像很多人使用 AI 一样.


合理的方式是, 外包团队出一个有经验的产品经理, 带着一些产品案例, 来去对餐厅老板进行一次结构化的访谈, 帮助老板梳理需求, 比如支付流程, 用户注册方式, APP入口等等.
这样一个访谈之后, 产品经理应该出具一份产品需求文档, 然后交给工程团队进行开发.

以上只是其中一种场景, 更抽象来说, 我们定义这个场景如下:

访谈需要有明确产出::
* 上例中产出是一个 PRD; 不同访谈可以有不同产出, 一个播客的产出就是对话本身, 一个心理咨询面诊的产出是诊断报告, 一个论文头脑风暴产出是大纲, 等等.
* 我们希望专注于生产力相关的场景, 产出是一种明确的交付

任务需要人类输入::
有些任务完全不需要人类, 那么就没有必要访谈. 上例中需要老板是因为他对自己餐厅有独特的了解.

需要访谈者的专业知识::
* 虽然苏格拉底也是非常好的提问者, 但苏在很多对话中, 对具体话题是没有回答者了解的, 所以他常常只能启发, 不能建构性的帮助
* 上例中, 进行访谈的产品经理在技术方面比老板更懂, 所以不只可以引导老板思路, 还可以给出方案供老板选择, 老板也更有意愿进行这个对话

NOTE: Axiia-启问是一个通用的访谈者框架, 可以打造各个领域的访谈者.


=== 愿景

我们希望 *启问* 可以成为人类与复杂工具之间的通用接口. 我们设想的未来是：用户只需表达他们的需求和目标，而不必深入了解工具的技术细节。AI将成为这个过程中的关键中介，理解用户的意图，掌握工具的复杂性，并将两者无缝连接。
